name: build

on:
  push:
    branch:
      - main
  pull_request:
    branch:
      - main

jobs:
  build-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install gcc make
      
      - name: Auto Generation
        run: |
          ./autogen.sh
      
      - name: configure
        run: |
          ./configure
      
      - name: make
        run: |
          make -j $(nproc)

      - name: make install
        run: |
          sudo make install